name: My Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name'
        required: true

jobs:
  build:
    if: ${{ github.event.inputs.branch_name == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch_name }}  # Use the provided branch name

      - name: Check 
        run: echo "this is triggerd"
