name: My Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name'
        required: true

jobs:
  build:
    if: ${{ github.event.inputs.branch_name == 'main' }}
    runs-on: ubuntu-latest

    steps:

      - name: Check 
        run: echo "this is triggerd"
